var skills: { [skill: string]: number } = {
	"Affinity Sliding": 1,
	"Botanist": 4,
	"Capture Master": 1,
	"Carving Master": 1,
	"Carving Pro": 1,
	"Constitution": 5,
	"Geologist": 3,
	"Good Luck": 3,
	"Hunger Resistance": 3,
	"Jump Master": 1,
	"Marathon Runner": 3,
	"Spiribird's Call": 1,
	"Stamina Surge": 3,
	"Wall Runner (Boost)": 1,
	"Wall Runner": 3,
	"Wind Mantle": 3,
	"Wirebug Whisperer": 3,
	"Bombardier": 3,
	"Free Meal": 3,
	"Item Prolonger": 3,
	"Mushroomancer": 3,
	"Recovery Up": 3,
	"Speed Eating": 3,
	"Wide-Range": 5,
	"Blood Rite": 3,
	"Bubbly Dance": 3,
	"Divine Blessing": 3,
	"Embolden": 3,
	"Evade Extender": 3,
	"Evade Window": 5,
	"Flinch Free": 3,
	"Furious": 3,
	"Guard Up": 3,
	"Guard": 5,
	"Guts": 3,
	"Intrepid Heart": 2,
	"Leap of Faith": 1,
	"Quick Sheathe": 3,
	"Recovery Speed": 3,
	"Redirection": 2,
	"Blast Resistance": 3,
	"Blight Resistance": 3,
	"Defiance": 5,
	"Earplugs": 5,
	"Hellfire Cloak": 4,
	"Muck Resistance": 2,
	"Paralysis Resistance": 3,
	"Poison Resistance": 3,
	"Quick Breath": 1,
	"Sleep Resistance": 3,
	"Stun Resistance": 3,
	"Tremor Resistance": 3,
	"Windproof": 3,
	"Attack Boost": 7,
	"Defense Boost": 7,
	"Dragon Resistance": 3,
	"Fire Resistance": 3,
	"Ice Resistance": 3,
	"Thunder Resistance": 3,
	"Water Resistance": 3,
	"Blast Attack": 3,
	"Charge Master": 3,
	"Diversion": 1,
	"Dragon Attack": 5,
	"Dragon Conversion": 3,
	"Fire Attack": 5,
	"Ice Attack": 5,
	"Master Mounter": 1,
	"Paralysis Attack": 3,
	"Partbreaker": 3,
	"Poison Attack": 3,
	"Sleep Attack": 3,
	"Slugger": 3,
	"Stamina Thief": 3,
	"Status Trigger": 3,
	"Thunder Attack": 5,
	"Water Attack": 5,
	"Adrenaline Rush": 3,
	"Agitator": 5,
	"Artillery": 3,
	"Berserk": 2,
	"Bladescale Hone": 3,
	"Bloodlust": 3,
	"Bludgeoner": 3,
	"Buildup Boost": 3,
	"Burst": 3,
	"Coalescence": 3,
	"Counterstrike": 3,
	"Critical Boost": 3,
	"Critical Draw": 3,
	"Critical Element": 3,
	"Critical Eye": 7,
	"Dereliction": 3,
	"Dragonheart": 5,
	"Element Exploit": 3,
	"Focus": 3,
	"Foray": 3,
	"Fortify": 1,
	"Frostcraft": 3,
	"Grinder (S)": 3,
	"Heroics": 5,
	"Latent Power": 5,
	"Mail of Hellfire": 3,
	"Maximum Might": 3,
	"Offensive Guard": 3,
	"Peak Performance": 3,
	"Powder Mantle": 3,
	"Power Prolonger": 3,
	"Punishing Draw": 3,
	"Resentment": 5,
	"Resuscitate": 3,
	"Sneak Attack": 3,
	"Strife": 3,
	"Weakness Exploit": 3,
	"Handicraft": 5,
	"Horn Maestro": 1,
	"Load Shells": 2,
	"Master's Touch": 3,
	"Mind's Eye": 3,
	"Protective Polish": 3,
	"Rapid Morph": 3,
	"Razor Sharp": 3,
	"Speed Sharpening": 3,
	"Ammo Up": 3,
	"Ballistics": 3,
	"Bow Charge Plus": 1,
	"Normal/Rapid Up": 3,
	"Pierce Up": 3,
	"Rapid Fire Up": 3,
	"Recoil Down": 3,
	"Reload Speed": 3,
	"Spare Shot": 3,
	"Special Ammo Boost": 2,
	"Spread Up": 3,
	"Steadiness": 3,
	"Tune-Up": 2,
	"Chameleos Blessing": 4,
	"Kushala Blessing": 4,
	"Stormsoul": 5,
	"Teostra Blessing": 4,
	"Thunder Alignment": 5,
	"Wind Alignment": 5,
	"LV1 Slot Skill": 7,
	"LV2 Slot Skill": 7,
	"LV3 Slot Skill": 7,
	"LV4 Slot Skill": 7
}